name: euler-inversion
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.12.*
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - black
  - flake8
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - xarray
  - netcdf4
  - numba
  - rich
  - ipywidgets
  # Fatiando
  - verde
  - pooch
  - pip:
    - git+https://github.com/fatiando/harmonica
