name: euler-inversion
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.12.*
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - pandas
  - geopandas==0.14.3
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - xarray
  - netcdf4 
  - numba
  - rich
  - ipywidgets
  - pyproj
  - pygmt
  - matplotlib-scalebar
  # Fatiando
  - verde
  - pooch
  - harmonica
  - pip:
    - line_profiler
    - black[jupyter]
