name: euler-inversion
dependencies:
    - python==3.10
    - pip
    - numpy
    - scipy
    - xarray
    - matplotlib
    - numba
    - jupyter
    - jupyterlab
    - harmonica
    - verde
    - ensaio
    - pooch
    - black
    - flake8
