name: euler-inversion
dependencies:
    - python==3.8
    - pip
    - numpy
    - scipy
    - xarray
    - matplotlib
    - numba
    - jupyter
    - jupyterlab
    - harmonica
    - pooch
    - verde
