name: euler-inversion
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.10.*
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - black
  - flake8
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - xarray
  - netcdf4
  - numba
  # Fatiando
  - harmonica
  - verde
  - ensaio
  - pooch
