name: euler-inversion
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.12.*
  - pip
  - conda-lock
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - pandas
  # For building latex documents
  - make
  - tectonic
  - latexdiff==1.3.2
  # Project specific dependencies
  - xarray
  - netcdf4
  - numba
  - rich
  - ipywidgets
  - pyproj
  - pygmt
  - matplotlib-scalebar
  - geopandas
  - fiona
  # Fatiando
  - verde
  - pooch
  - harmonica
  - pip:
    - black[jupyter]
